### ISSUE TITLE
Select better package name

### ISSUE THREAD

**Issue by nerdcha** [MattCowgill/getabs#6]
This is great, in concept and execution, but it needs a catchier name.

My suggestions:

- `absrd` (`ABSRd`, `ABSuRd`…?)
- `EightMinuteAbs`
- `ABSolutePower`
- `absorb`
- `RPackageInterfaceForTheABSBecauseTheyAreTooPoorlyFundedToHaveAProperAPI`

**Comment by MattCowgill** [comment]
FUN FACT: the name is gonna chance to readabs soon, it's merging with https://cran.r-project.org/web/packages/readabs/index.html
